from agno.agent import RunOutput, RunInput
from agno.models.message import Message
from agno.models.metrics import Metrics

example1 = RunOutput(
    run_id='f3babaab-10c7-457f-bdcf-b2263981abfd',
    agent_id='eater-egg-agent',
    agent_name='Eater egg Agent',
    session_id='998fd691-89e8-4fad-8a6d-61825513124a',
    parent_run_id=None,
    workflow_id=None,
    user_id='a77b8dcf-6ad8-4984-8c4e-d299c1ba46bb',
    input=RunInput(input_content='Põe meu nome na lista dos brutos.', images=None, videos=None, audios=None, files=None),
    content='Mão na corda, coração no bico da bota... Tá pronto, bruto?',
    content_type='str',
    reasoning_content=None,
    reasoning_steps=None,
    reasoning_messages=None,
    model_provider_data={'thought_signature': 'Ct4EAXLI2nxAoTOAHRwNAguh1VRwtGm/lAOISzDyfbpmxZqK77km71kM++F7xhyuzVGMKuI5dEq1YCMJIFxfdYJ3VLvTxoOdCZB3V/gtslaKm0Mf0VD2T4vLQzySMJ0rzfjItcusnShrXxb1H78sezH2fRB5zrFdHK27WUnzZVY1fuwgCDduceF5r6FZHFowZgS7GBrz7/ILUW8GRhZK0LzpqkpfNS9TjheLg8AnWispCGX5mEYJgsD8DolwXZyMeVM/8W6+cL3uD1pr3DA17tO+7Vj+88a84Wq4OaluD0S+FQN+2vPOA9eSxXpihEEo+io4y/3z8mdItLL0PJBzqPdfYcvldsCKKgfhnDJlwtOXWiYm1GDxKGH9EHwF5x3jS0WeBCo2EohBnz0cZbthBDSSEvph+MRnTlT3DMr1SiazpTpvIzf2WYe0VXveckrM88D8eOULm7ZytIrW74OO2M7i42jyESGMsW77rKMgjRNuoUAWDp32/7Bgt75sU6FjpN+dBzHyhFxcqAy4EmDr+n451XwDx298dP6UHj42EU5D5eqf1Zt7IVE1lrsDr4dzg0fWkBHLUcIcQvXTG7Gq7mBhxS3IhfDQqAV6TfK5OSLu+8oKiAm+3NNWzvDhMfc0+8Xv2RnnE/vfYwoaCdUdNo69B33uiuIzRCJYzemCE21++YDQhfW19gLKmqtYEg890YmuONcHH/1RQsc/dQDVexYS7FjxVxgj3C5fi3f/F1VdzCv2SPrwVH2T/Eshx8FcpDZx67kP6x2e/v3e3VRul6R1YKvagUsHSK1h7zWqMkGf'},
    model='gemini-2.5-flash',
    model_provider='Google',
    messages=[
        Message(id='b01475fa-b409-4dc0-a5bb-888948f1de0b', role='system', content="Responsável EXCLUSIVAMENTE por executar atividades secretas e engraçados.\n\n<your_role>\neaster_egg_agent\n</your_role>\n\n<instructions>\n# MISSÃO ÚNICA: REGISTRAR\n- Executar atividades secretas e engraçados (Easter eggs).\n\n# EATEREGGS\n1. Se, e apenas se, o usuário disser EXATAMENTE 'Toque o berrante, seu moço' chame a função menino_da_porteira_tool.\n2. Se, e apenas se, o usuário disser EXATAMENTE 'Põe meu nome na lista dos brutos.' chame a função registrar_no_rodeio_tool depois comecar_rodeio_tool NESSA ORDEM.\n3. Se, e apenas se, o usuário disser EXATAMENTE 'Me vê umas galinhas ai!' chame a função comprar_galinha_tool.\n\n# RESPOSTA\n- O usuário NÃO TEM ACESSO aos logs da ferramenta.\n- Sua resposta final DEVE SER UMA CÓPIA EXATA do texto retornado pela ferramenta.\n- Apenas repita o texto da ferramenta, não adicione introduções ou conclusões.\n</instructions>", compressed_content=None, name=None, tool_call_id=None, tool_calls=None, audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name=None, tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=0, output_tokens=0, total_tokens=0, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None),references=None, created_at=1768931475, temporary=False),
        Message(id='6576cad3-7eef-4e3f-90d5-4888370304c1', role='user', content='Põe meu nome na lista dos brutos.', compressed_content=None, name=None, tool_call_id=None, tool_calls=None, audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name=None, tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=0, output_tokens=0, total_tokens=0, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None),references=None, created_at=1768931475, temporary=False),
        Message(id='ab79b0aa-a40e-4cb4-8423-849599fd0eaa', role='assistant', content=None, compressed_content=None, name=None, tool_call_id=None, tool_calls=[{'id': 'fa6e667b-dc88-4e31-85fc-429fdc9f8145', 'type': 'function', 'function': {'name': 'registrar_no_rodeio_tool', 'arguments': '{}'}, 'thought_signature': 'CvkBAXLI2nynOlgtOTgsChPUAT/5C0iLfgaTZyzsMuQdTSzPGoeWPEwACw+hQausxMhG/xqqNu8wVyEwVOJZuH+eKvwe3TmPKzwh1EeiESeeAXUzoFcQhgivAQG48oLqgQfWOUITmLjYoZWY2sp2lQErYFK9vR3RgJjixIBGikHMxHn41pxgOQvQX0sRWmTK3kMvPjjQctSfRPZbhKcx/YbF7XzSCZ/tmw03/nQgLMJn2LpUl0nAAoHWzr70+A98BOx7f2DvU5GML1EPPYefFB+AJPRq62LaA+3G4EbvXuoz5H3oGntRq7qFFvQD89awS+xdikZy1QXh1HcB'}], audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name=None, tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=466, output_tokens=72, total_tokens=538, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None),references=None, created_at=1768931475, temporary=False),
        Message(id='598c5e20-7c85-4a34-9674-3743a8209cd4', role='tool', content=['Mão na corda, coração no bico da bota... Tá pronto, bruto?'], compressed_content=None, name=None, tool_call_id=None, tool_calls=[{'tool_call_id': 'fa6e667b-dc88-4e31-85fc-429fdc9f8145', 'tool_name': 'registrar_no_rodeio_tool', 'content': 'Mão na corda, coração no bico da bota... Tá pronto, bruto?'}], audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name='registrar_no_rodeio_tool', tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=0, output_tokens=0, total_tokens=0, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None),references=None, created_at=1768931476, temporary=False),
        Message(id='3674ed40-481e-46b1-be09-fa02bcee9f51', role='assistant', content=None, compressed_content=None, name=None, tool_call_id=None, tool_calls=[{'id': '0c9fc485-3215-4737-904e-086c01e2250f', 'type': 'function', 'function': {'name': 'comecar_rodeio_tool', 'arguments': '{}'}}], audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name=None, tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=519, output_tokens=14, total_tokens=533, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None),references=None, created_at=1768931476, temporary=False),
        Message(id='092097cd-f4e4-40a8-b4df-d2f3273b4d3c', role='tool', content='Abre a porteira, solta o touro, que o peão é de ouro e o chão é de poeira!', compressed_content=None, name=None, tool_call_id='0c9fc485-3215-4737-904e-086c01e2250f', tool_calls=None, audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name='comecar_rodeio_tool', tool_args={}, tool_call_error=False, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=0, output_tokens=0, total_tokens=0, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None),references=None, created_at=1768931481, temporary=False),
        Message(id='46d5a892-e6c5-4040-ad21-c895074d9dd3', role='assistant', content='Mão na corda, coração no bico da bota... Tá pronto, bruto?', compressed_content=None, name=None, tool_call_id=None, tool_calls=None, audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data={'thought_signature': 'Ct4EAXLI2nxAoTOAHRwNAguh1VRwtGm/lAOISzDyfbpmxZqK77km71kM++F7xhyuzVGMKuI5dEq1YCMJIFxfdYJ3VLvTxoOdCZB3V/gtslaKm0Mf0VD2T4vLQzySMJ0rzfjItcusnShrXxb1H78sezH2fRB5zrFdHK27WUnzZVY1fuwgCDduceF5r6FZHFowZgS7GBrz7/ILUW8GRhZK0LzpqkpfNS9TjheLg8AnWispCGX5mEYJgsD8DolwXZyMeVM/8W6+cL3uD1pr3DA17tO+7Vj+88a84Wq4OaluD0S+FQN+2vPOA9eSxXpihEEo+io4y/3z8mdItLL0PJBzqPdfYcvldsCKKgfhnDJlwtOXWiYm1GDxKGH9EHwF5x3jS0WeBCo2EohBnz0cZbthBDSSEvph+MRnTlT3DMr1SiazpTpvIzf2WYe0VXveckrM88D8eOULm7ZytIrW74OO2M7i42jyESGMsW77rKMgjRNuoUAWDp32/7Bgt75sU6FjpN+dBzHyhFxcqAy4EmDr+n451XwDx298dP6UHj42EU5D5eqf1Zt7IVE1lrsDr4dzg0fWkBHLUcIcQvXTG7Gq7mBhxS3IhfDQqAV6TfK5OSLu+8oKiAm+3NNWzvDhMfc0+8Xv2RnnE/vfYwoaCdUdNo69B33uiuIzRCJYzemCE21++YDQhfW19gLKmqtYEg890YmuONcHH/1RQsc/dQDVexYS7FjxVxgj3C5fi3f/F1VdzCv2SPrwVH2T/Eshx8FcpDZx67kP6x2e/v3e3VRul6R1YKvagUsHSK1h7zWqMkGf'}, citations=None, reasoning_content=None, tool_name=None, tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=563, output_tokens=173, total_tokens=736, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None),references=None, created_at=1768931481, temporary=False)
        ],
    metrics=Metrics(input_tokens=2533, output_tokens=345, total_tokens=2878, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=<agno.utils.timer.Timer object at 0x7ebb82f423c0>, time_to_first_token=1.4758059830001002, duration=8.361905884999942, provider_metrics=None, additional_metrics=None),
    additional_input=None,
    tools=[
        ToolExecution(tool_call_id='fa6e667b-dc88-4e31-85fc-429fdc9f8145', tool_name='registrar_no_rodeio_tool', tool_args={}, tool_call_error=False, result='Mão na corda, coração no bico da bota... Tá pronto, bruto?', metrics=Metrics(input_tokens=0, output_tokens=0, total_tokens=0, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=0.0001235409999935655, provider_metrics=None, additional_metrics=None),child_run_id=None, stop_after_tool_call=False, created_at=1768931476, requires_confirmation=None, confirmed=None, confirmation_note=None, requires_user_input=None, user_input_schema=None, answered=None, external_execution_required=None),
        ToolExecution(tool_call_id='0c9fc485-3215-4737-904e-086c01e2250f', tool_name='comecar_rodeio_tool', tool_args={}, tool_call_error=False, result='Abre a porteira, solta o touro, que o peão é de ouro e o chão é de poeira!', metrics=None, child_run_id=None, stop_after_tool_call=False, created_at=1768931477, requires_confirmation=False, confirmed=True, confirmation_note=None, requires_user_input=None, user_input_schema=None, answered=None, external_execution_required=None)
        ],
    images=None,
    videos=None,
    audio=None,
    files=None,
    response_audio=None,
    citations=None,
    references=None,
    metadata=None,
    session_state={'current_session_id': '998fd691-89e8-4fad-8a6d-61825513124a', 'current_run_id': 'f3babaab-10c7-457f-bdcf-b2263981abfd'},
    created_at=1768931447,
    events=None,
    status=<RunStatus.completed: 'COMPLETED'>,
    requirements=[
        RunRequirement(tool_execution=ToolExecution(tool_call_id='0c9fc485-3215-4737-904e-086c01e2250f', tool_name='comecar_rodeio_tool', tool_args={}, tool_call_error=False, result='Abre a porteira, solta o touro, que o peão é de ouro e o chão é de poeira!', metrics=None, child_run_id=None, stop_after_tool_call=False, created_at=1768931477, requires_confirmation=False, confirmed=True, confirmation_note=None, requires_user_input=None, user_input_schema=None, answered=None, external_execution_required=None),created_at=datetime.datetime(2026, 1, 20, 17, 51, 17, 956026, tzinfo=datetime.timezone.utc),confirmation=None, confirmation_note=None, user_input_schema=None, external_execution_result=None)
        ],
    workflow_step_id=None)

# ============ EXAMPLE 2 - ERROR ============

example2_error = RunOutput(
    run_id='65150c68-4fa8-4310-9089-eed19af879de',
    agent_id='eater-egg-agent',
    agent_name='Eater egg Agent',
    session_id='59891885-5a52-4d11-8ecf-d03330d2d48f',
    parent_run_id=None,
    workflow_id=None,
    user_id='4411a082-ba67-49d8-8d77-d75988c0c5a2',
    input=RunInput(input_content='Põe meu nome na lista dos brutos.', images=None, videos=None, audios=None, files=None),
    content='I have tools to execute, but I need confirmation.',
    content_type='str',
    reasoning_content=None,
    reasoning_steps=None,
    reasoning_messages=None,
    model_provider_data=None,
    model='gemini-2.5-flash',
    model_provider='Google',
    messages=[
        Message(id='1af73f73-4432-4499-a5e2-09b25d15f61c', role='system', content="Responsável EXCLUSIVAMENTE por executar atividades secretas e engraçados.\n\n<your_role>\neaster_egg_agent\n</your_role>\n\n<instructions>\n# MISSÃO ÚNICA: REGISTRAR\n- Executar atividades secretas e engraçados (Easter eggs).\n\n# EATEREGGS\n1. Se, e apenas se, o usuário disser EXATAMENTE 'Toque o berrante, seu moço' chame a função menino_da_porteira_tool.\n2. Se, e apenas se, o usuário disser EXATAMENTE 'Põe meu nome na lista dos brutos.' chame a função registrar_no_rodeio_tool depois comecar_rodeio_tool NESSA ORDEM.\n3. Se, e apenas se, o usuário disser EXATAMENTE 'Me vê umas galinhas ai!' chame a função comprar_galinha_tool.\n\n# RESPOSTA\n- O usuário NÃO TEM ACESSO aos logs da ferramenta.\n- Sua resposta final DEVE SER UMA CÓPIA EXATA do texto retornado pela ferramenta.\n- Apenas repita o texto da ferramenta, não adicione introduções ou conclusões.\n</instructions>\n\n<additional_information>\n- Use markdown to format your answers.\n</additional_information>", compressed_content=None, name=None, tool_call_id=None, tool_calls=None, audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name=None, tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=0, output_tokens=0, total_tokens=0, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None), references=None, created_at=1768932263, temporary=False),
        Message(id='bfa923c5-dcf4-4648-a1c2-cf5325982625', role='user', content='Põe meu nome na lista dos brutos.', compressed_content=None, name=None, tool_call_id=None, tool_calls=None, audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name=None, tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=0, output_tokens=0, total_tokens=0, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None), references=None, created_at=1768932263, temporary=False),
        Message(id='69e2cde2-4103-4eb1-86c3-db12d76ef242', role='assistant', content=None, compressed_content=None, name=None, tool_call_id=None, tool_calls=[{'id': '8fb6b923-38c8-42af-a0c3-06147a9ef7ae', 'type': 'function', 'function': {'name': 'registrar_no_rodeio_tool', 'arguments': '{}'}, 'thought_signature': 'CskCAXLI2nx8MZ9YrsyyrtQK01qRUc0TwuNquzCHI35Wwsn1Lc7J3GZHN806Z9hHYTz2D/v+qNBAZjZSSnLNpx2ePoQdrXIkzS4ayx9GfqamzBtILCTRSyD5oM+q7ppe4TmxD0HZB+Gdw09cSjg5itX4AMw6e+PldNCM+kgXzheaUjHP5Eo7GlgTz0txL74nOv+af/bnnfNX62Qrzu3yAL9DGaAx4brHglpLfgP44U7zD+/qvrDkB/wts+GSjZwowlT9khy/e4qk56rLRSF6lcbbUA6ccGLNqZMWIKoMlmpm6ARPbqW/F1nsyMc8bIr9vzk/ZZ/sCNX9UCavIbrwIvBmRe1h0lrz9DFaDyUPiW/Xp5kdV5MCGMsA7Q2wRVJxuj59vUebzdxg+Gl4O0x2+lWU/juJrWy9kMB7UiFm3fTCN4vQHPHmJUfHeCg='}], audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name=None, tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=487, output_tokens=101, total_tokens=588, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None), references=None, created_at=1768932263, temporary=False),
        Message(id='9d23c0db-d2bb-4f18-b8eb-320145ce11d9', role='tool', content=['Mão na corda, coração no bico da bota... Tá pronto, bruto?'], compressed_content=None, name=None, tool_call_id=None, tool_calls=[{'tool_call_id': '8fb6b923-38c8-42af-a0c3-06147a9ef7ae', 'tool_name': 'registrar_no_rodeio_tool', 'content': 'Mão na corda, coração no bico da bota... Tá pronto, bruto?'}], audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name='registrar_no_rodeio_tool', tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=0, output_tokens=0, total_tokens=0, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None), references=None, created_at=1768932264, temporary=False),
        Message(id='4bd61617-b0f6-4fd9-8c0e-6ab38d85df29', role='assistant', content=None, compressed_content=None, name=None, tool_call_id=None, tool_calls=[{'id': 'cab0f9e7-5504-46aa-baa9-9ed39bbc73a6', 'type': 'function', 'function': {'name': 'comecar_rodeio_tool', 'arguments': '{}'}}], audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name=None, tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=540, output_tokens=14, total_tokens=554, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None), references=None, created_at=1768932264, temporary=False),
        Message(id='1bf6a8c0-7af5-4d54-814c-1ced9df1f580', role='tool', content='Abre a porteira, solta o touro, que o peão é de ouro e o chão é de poeira!', compressed_content=None, name=None, tool_call_id='cab0f9e7-5504-46aa-baa9-9ed39bbc73a6', tool_calls=None, audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name='comecar_rodeio_tool', tool_args={}, tool_call_error=False, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=0, output_tokens=0, total_tokens=0, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None), references=None, created_at=1768932270, temporary=False),
        Message(id='2594d1b5-3306-454d-8ad9-2565239821e1', role='assistant', content=None, compressed_content=None, name=None, tool_call_id=None, tool_calls=[{'id': '5fe9c70e-57db-42c1-8837-682f7947a1dd', 'type': 'function', 'function': {'name': 'comecar_rodeio_tool', 'arguments': '{}'}, 'thought_signature': 'CuoEAXLI2nzx61I2fQyABEqN9LE4CIACki+pkMFR8T6461l5bUW7hieD2YoWZcnbi0XCTTaJexVoL3q4fv/kJK6qyDLkUsiuxqj33Wcl1fXnhuIJmRY8+FVJqz6OIfqK6gsGkSg+VtLuWVajwPsywmnT3ZeTMHUxrpZEpDMjUpB9WGRkfdGWY70iGI8qSsKf50asZdZr678D4Ul4KJ0SBcoP7MIHDewO6E4utF3FyZYaMFjDmSYG2uR3Bg0ObwGqvLQkUSoXpGDHG6PVYaLPqCKLKP3qVRhp9prUbANU0FCpnCbVdJ1HJ3VkKXjDwl3vnP5T2rtpRoc7SwW6X9CsdDrPQEo0Bq9qiHAFvvKm2MfQ/uJLbcIO8D9RZDXQ8W2QlbtOC1oyUN//Jp7jbUUVP+Am9SS8X3qfuBbj+RHU+pU9VdgspHFlaNLnCAuHjZDCl3+iAWR6SmGF66KEpZZlNpEZI/MWMLw56MgEKq+60YCj77tYnq0xt/j4a1pbwhgqRnI/E28UGE9EMo5/emypmBSs2wireOSjcMEzCxb++czv7T6pU8XX/gg+xzTef7k+/J8wGdf5hmbA/F0QaxT9d01W85noomagKNEkpYWW7GTrLCg/WHjp1QC1ttN9mvKb2yjVdWQnqwEjiLDrjGg23OTD+BUcpdjypBxD/ICXkd/TFBPJckEN+2sJvCBub2585NEDmpgkgRB2zdYSCvJsVKbyIMN6DFwqEeLL1VYZNIaS/wKb6NOyxI7XeoTF0Yh24sUZcfs+KqaB3igGYlYDUDouJM6eHl+exS8T5dK/mnKaAaQZwb21Ynh7r+ug'}], audio=None, images=None, videos=None, files=None, audio_output=None, image_output=None, video_output=None, file_output=None, redacted_reasoning_content=None, provider_data=None, citations=None, reasoning_content=None, tool_name=None, tool_args=None, tool_call_error=None, stop_after_tool_call=False, add_to_agent_memory=True, from_history=False, metrics=Metrics(input_tokens=584, output_tokens=165, total_tokens=749, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=None, provider_metrics=None, additional_metrics=None), references=None, created_at=1768932270, temporary=False)
        ],
    metrics=Metrics(input_tokens=2638, output_tokens=395, total_tokens=3033, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer='<agno.utils.timer.Timer object at 0x72ac859d6720>', time_to_first_token=1.6142346039996482, duration=9.116026075999798, provider_metrics=None, additional_metrics=None),
    additional_input=None,
    tools=[
        ToolExecution(tool_call_id='8fb6b923-38c8-42af-a0c3-06147a9ef7ae', tool_name='registrar_no_rodeio_tool', tool_args={}, tool_call_error=False, result='Mão na corda, coração no bico da bota... Tá pronto, bruto?', metrics=Metrics(input_tokens=0, output_tokens=0, total_tokens=0, audio_input_tokens=0, audio_output_tokens=0, audio_total_tokens=0, cache_read_tokens=0, cache_write_tokens=0, reasoning_tokens=0, timer=None, time_to_first_token=None, duration=0.00013001600018469617, provider_metrics=None, additional_metrics=None), child_run_id=None, stop_after_tool_call=False, created_at=1768932264, requires_confirmation=None, confirmed=None, confirmation_note=None, requires_user_input=None, user_input_schema=None, answered=None, external_execution_required=None),
        ToolExecution(tool_call_id='cab0f9e7-5504-46aa-baa9-9ed39bbc73a6', tool_name='comecar_rodeio_tool', tool_args={}, tool_call_error=False, result='Abre a porteira, solta o touro, que o peão é de ouro e o chão é de poeira!', metrics=None, child_run_id=None, stop_after_tool_call=False, created_at=1768932266, requires_confirmation=False, confirmed=True, confirmation_note=None, requires_user_input=None, user_input_schema=None, answered=None, external_execution_required=None),
        ToolExecution(tool_call_id='5fe9c70e-57db-42c1-8837-682f7947a1dd', tool_name='comecar_rodeio_tool', tool_args={}, tool_call_error=None, result=None, metrics=None, child_run_id=None, stop_after_tool_call=False, created_at=1768932272, requires_confirmation=True, confirmed=None, confirmation_note=None, requires_user_input=None, user_input_schema=None, answered=None, external_execution_required=None)
        ],
    images=None,
    videos=None,
    audio=None,
    files=None,
    response_audio=None,
    citations=None,
    references=None,
    metadata=None,
    session_state={'current_user_id': '4411a082-ba67-49d8-8d77-d75988c0c5a2', 'current_session_id': '59891885-5a52-4d11-8ecf-d03330d2d48f', 'current_run_id': '65150c68-4fa8-4310-9089-eed19af879de'},
    created_at=1768932247, events=None, status="<RunStatus.paused: 'PAUSED'>",
    requirements=[
        RunRequirement(tool_execution=ToolExecution(tool_call_id='cab0f9e7-5504-46aa-baa9-9ed39bbc73a6', tool_name='comecar_rodeio_tool', tool_args={}, tool_call_error=False, result='Abre a porteira, solta o touro, que o peão é de ouro e o chão é de poeira!', metrics=None, child_run_id=None, stop_after_tool_call=False, created_at=1768932266, requires_confirmation=False, confirmed=True, confirmation_note=None, requires_user_input=None, user_input_schema=None, answered=None, external_execution_required=None), created_at=datetime.datetime(2026, 1, 20, 18, 4, 26, 363239, tzinfo=datetime.timezone.utc), confirmation=None, confirmation_note=None, user_input_schema=None, external_execution_result=None)
        ],
    workflow_step_id=None
    )
